version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-knot-organization
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
